import type { Metadata } from 'next';
import './globals.css';
import Header from './components/Header/Header';
import Footer from './components/Footer/Footer';
import Container from './components/Container/Container';
import s from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={s.root}>
        <Header page={''} />
        <main className={s.main}>
          <Container>{children}</Container>
        </main>
        <Footer />
      </body>
    </html>
  );
}
